apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollution-service
  labels:
    app: pollution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pollution-service
  template:
    metadata:
      labels:
        app: pollution-service
    spec:
      containers:
        - name: pollution-service
          image: javiimiralles/pollution-service:v1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

