apiVersion: v1
kind: ConfigMap
metadata:
  name: bike-service-api-config
data:
  SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
  SERVICE_BIKE_DATA_URL: "http://bike-data:8084/api/v1"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8090/realms/final-twcam"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8090/realms/final-twcam/protocol/openid-connect/certs"