apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: bike-service
  template:
    metadata:
      labels:
        app: bike-service
    spec:
      hostAliases:
        - ip: "10.104.19.99"
          hostnames:
            - "keycloak.local"
      containers:
        - name: bike-service
          image: javiimiralles/bike-service:v1.7
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bike-service-api-config
            - secretRef:
                name: bike-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
