apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-service
  labels:
    app: city-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-service
  template:
    metadata:
      labels:
        app: city-service
    spec:
      containers:
        - name: city-service
          image: javiimiralles/city-service:v1.0
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: KEYCLOAK_SERVICIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: city-service-secret
                  key: keycloak-servicio-token