apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-polucion
spec:
  serviceName: mysql-polucion
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-polucion-config
            - secretRef:
                name: mysql-polucion-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-polucion-pvc
        - name: initdb
          configMap:
            name: mysql-polucion-init-config
