apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-bicicletas-pvc
spec:
  volumeName: mongo-bicicletas-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
