apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollution-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: pollution-service
  template:
    metadata:
      labels:
        app: pollution-service
    spec:
      hostAliases:
        - ip: "10.104.19.99"
          hostnames:
            - "keycloak.local"
      containers:
        - name: pollution-service
          image: javiimiralles/pollution-service:v1.4
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: pollution-service-api-config
            - secretRef:
                name: pollution-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
