apiVersion: v1
kind: Service
metadata:
  name: pollution-service
spec:
  type: ClusterIP
  selector:
    app: pollution-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
