apiVersion: v1
kind: ConfigMap
metadata:
  name: city-service-config
data:
  SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
  BIKE_SERVICE_URL: "http://bike-service:8080/api/v1"
  POLLUTION_SERVICE_URL: "http://pollution-service:8081/api/v1"
  SPRING_DATA_MONGODB_URI: "mongodb://mongo-ayuntamiento:27017/ayuntamiento_nosql"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak.local:30129/realms/final-twcam"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak.local:8089/realms/final-twcam/protocol/openid-connect/certs"