apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: city-service
  template:
    metadata:
      labels:
        app: city-service
    spec:
      hostAliases:
        - ip: "10.104.19.99"
          hostnames:
            - "keycloak.local"
      containers:
        - name: city-service
          image: javiimiralles/city-service:v1.3
          ports:
            - containerPort: 8082
          envFrom:
          - configMapRef:
              name: city-service-config
          - secretRef:
              name: city-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
